name: Laravel CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Deploy to server 🚀
        uses: appleboy/ssh-action@master
        with:
          host: 103.210.69.72
          port: 22
          username: User8
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/User8/transgo-backend
            git pull origin main
            git status
